### ISSUE TITLE
Manager Application Form

### ISSUE THREAD

**Issue by jerok-kim** [Final-DAMDA/BE_DAMDA#10]
## Description

- User가 Manager에 지원할 수 있는 폼과 관련된 기능을 만든다.

## Todo List

- [ ] Manager domain 생성하기
- [ ] 해당 테이블 생성하기
- [ ] 폼 자체를 변경할 수 있게 할 것인가
- [ ] 테스트
