### ISSUE TITLE
Reservation Form 

### ISSUE THREAD

**Issue by kimjaewoo2233** [Final-DAMDA/BE_DAMDA#4]
## Description
 - 어드민이 마음대로 수정할 수 있도록 폼을 수정할 수 있고, 필수 데이터에 대한 항목은 항상 존재해야한다.
## Todo List

- [ ] CommonResponse, CommonException 생성하기
- [ ] 해당 테이블 생성하기 
- [ ]  데이터가 자유롭게 변환이 가능한가
- [ ] 테스트
